server:
    port: 8888

spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/ArturPanosyan/config-repo
                    clone-on-start: true

eureka:
    instance:
        hostname: localhost
    client:
        register-with-eureka: false
        fetch-registry: false